name = "cloudflare-d1-backups-example"
main = "src/index.ts"
compatibility_date = "2023-04-07"
usage_model = "bundled"
node_compat = true

[triggers]
crons = [ "0 * * * *" ]

[[ d1_databases ]]
binding = "DATABASE"
database_name = "cloudflare-d1-backups"
database_id = "9569a088-ddb7-408b-8ede-a12caafecf09"

[[ r2_buckets ]]
binding = "BUCKET"
bucket_name = "cloudflare-d1-backups"
preview_bucket_name = "cloudflare-d1-backups-local"
